import { test, expect } from '@playwright/test';
test.skip(!process.env.TEST_DATABASE_URL, 'Requires real disposable PostgreSQL');
// Dedicated server has explicit fake model/FX adapters. Never live integration/quality proof.
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAFElEQVR4nGOsmBbAgA0wYRUdtBIAFfMBbilI1DUAAAAASUVORK5CYII=', 'base64');
for (const mobile of [false, true]) test(`explicit fake A1/FX: actual PostgreSQL correction/reopen/privacy ${mobile ? 'mobile' : 'desktop'}`, async ({ page, context }) => {
  if (mobile) await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('http://127.0.0.1:5174');
  await page.getByLabel('Describe your report').fill('London 1–4 October 2026 for a client workshop');
  await page.getByRole('button', { name: 'Propose report', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm and create report' }).click();
  const evidence = page.getByRole('region', { name: 'Workspace evidence' });
  await evidence.getByLabel('Workspace files').setInputFiles({ name: 'synthetic.png', mimeType: 'image/png', buffer: png });
  await evidence.getByRole('button', { name: 'Upload evidence' }).click();
  await expect(evidence.getByText('Validated · retained', { exact: true })).toBeVisible();
  const expenses = page.getByRole('region', { name: 'Expense workspace' });
  await expenses.getByLabel('Selected receipt', { exact: true }).selectOption({ label: 'synthetic.png' });
  await expenses.getByRole('button', { name: 'Prepare selected receipt' }).click();
  await expect(page.getByRole('button', { name: 'Open expense', exact: true })).toBeVisible();
  await expect(expenses.getByLabel('Meal type', { exact: true })).toBeVisible();
  await expect(expenses.getByRole('img', { name: 'Selected original receipt' })).toBeVisible();
  await expect(expenses.getByLabel('VAT (optional)', { exact: true })).toHaveValue('');
  await expenses.getByLabel('Meal type', { exact: true }).selectOption('dinner');
  await expenses.locator('#expense-confirm-facts').check();
  await expenses.getByRole('button', { name: 'Save corrections' }).click();
  await expect(expenses.getByText('Adjusted to policy limit', { exact: false })).toBeVisible();
  await expect(expenses.getByText('£62.00', { exact: true })).toBeVisible();
  await expect(expenses.getByText('£50.00', { exact: true })).toBeVisible();
  await expect(expenses.getByText('£12.00', { exact: true })).toBeVisible();
  await page.reload();
  await expect(expenses.getByRole('button', { name: 'Synthetic Kitchen', exact: false })).toBeVisible();
  await expenses.getByRole('button', { name: 'Synthetic Kitchen', exact: false }).click();
  await expect(expenses.locator('#expense-mealType')).toHaveValue('dinner');
  await expenses.locator('#expense-originalAmount').fill('75.00');
  await expenses.locator('#expense-transactionCurrency').fill('EUR');
  await expenses.locator('#expense-confirm-facts').check();
  await expenses.getByRole('button', { name: 'Save corrections' }).click();
  await expect(expenses.getByText('£60.00', { exact: true })).toBeVisible();
  await expenses.getByRole('button', { name: 'Retry extraction', exact: true }).click();
  await expect(expenses.locator('#expense-originalAmount')).toHaveValue('75.00');
  await expect(expenses.locator('#expense-mealType')).toHaveValue('dinner');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const original = await expenses.getByRole('link', { name: 'Download original receipt' }).getAttribute('href');
  expect(await (await context.request.get('http://127.0.0.1:5174' + original)).body()).toEqual(png);
  await page.getByRole('button', { name: 'Manager', exact: true }).click();
  await expect(expenses).toHaveCount(0);
  expect((await context.request.get('http://127.0.0.1:5174' + original)).status()).toBe(403);
});
